name: "Relatório de Bug"
description: Crie um novo chamado para relatar um bug.
title: "[BUG] - <título>"
labels:
  - "bug"

body:
  - type: textarea
    id: description
    attributes:
      label: "Descrição"
      description: Informe uma descrição clara e objetiva do problema.
      placeholder: Descrição curta e objetiva do incidente...
    validations:
      required: true

  - type: input
    id: reprod-url
    attributes:
      label: "URL de Reprodução"
      description: Informe a URL do GitHub ou outro link que ajude a reproduzir o problema.
      placeholder: ex. https://github.com/USUARIO/NOME-DO-REPOSITORIO
    validations:
      required: true

  - type: textarea
    id: reprod
    attributes:
      label: "Passos para Reprodução"
      description: Descreva claramente os passos necessários para reproduzir o problema.
      value: |
        1. Acesse '...'
        2. Clique em '...'
        3. Role a página até '...'
        4. Veja o erro
      render: bash
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Capturas de Tela"
      description: Se aplicável, adicione capturas de tela para ajudar a explicar o problema.
      value: |
        ![DESCRIÇÃO](LINK.png)
      render: bash
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Copie e cole qualquer saída de log relevante. O conteúdo será formatado automaticamente como código, então não é necessário usar crases.
      render: bash
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: "Navegadores"
      description: Em quais navegadores o problema está ocorrendo?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: "Sistema Operacional"
      description: Qual é o ambiente impactado?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
